// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAE5cMRrkYKlGfTAWrxmEaTLAmI5_XFJ-0',
    appId: '1:880296121572:web:c33fb301ef3c76e4de88f1',
    messagingSenderId: '880296121572',
    projectId: 'ecommersapp-ed022',
    authDomain: 'ecommersapp-ed022.firebaseapp.com',
    storageBucket: 'ecommersapp-ed022.appspot.com',
    measurementId: 'G-DNYEEFJWH4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDP2MFV6okt6Siy0WUeYo8nS2GNFA9dxRE',
    appId: '1:880296121572:android:0c3152810d09dff6de88f1',
    messagingSenderId: '880296121572',
    projectId: 'ecommersapp-ed022',
    storageBucket: 'ecommersapp-ed022.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD51qulT5KgY6wuYi4nY8GxyzJAfbMFFIA',
    appId: '1:880296121572:ios:f8cd437701779f9fde88f1',
    messagingSenderId: '880296121572',
    projectId: 'ecommersapp-ed022',
    storageBucket: 'ecommersapp-ed022.appspot.com',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD51qulT5KgY6wuYi4nY8GxyzJAfbMFFIA',
    appId: '1:880296121572:ios:f8cd437701779f9fde88f1',
    messagingSenderId: '880296121572',
    projectId: 'ecommersapp-ed022',
    storageBucket: 'ecommersapp-ed022.appspot.com',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAE5cMRrkYKlGfTAWrxmEaTLAmI5_XFJ-0',
    appId: '1:880296121572:web:c6b7362b7bc4398ade88f1',
    messagingSenderId: '880296121572',
    projectId: 'ecommersapp-ed022',
    authDomain: 'ecommersapp-ed022.firebaseapp.com',
    storageBucket: 'ecommersapp-ed022.appspot.com',
    measurementId: 'G-3YTRPLZX45',
  );
}
